const categories = [
  { value: 'Art Commissions', label: 'Art Commissions' },
  { value: 'Artistic Resources', label: 'Artistic Resources' },
  { value: 'Auto Parts / Repair', label: 'Auto Parts / Repair' },
  { value: 'Child Care', label: 'Child Care' },
  { value: 'Clothing Donations', label: 'Clothing Donations' },
  { value: 'Community Gatherings', label: 'Community Gatherings'},
  { value: 'COVID Supplies', label: 'COVID Supplies' },
  { value: 'Disability Assistance', label: 'Disability Assistance' },
  { value: 'Electrical Help', label: 'Electrical Help' },
  { value: 'Energy Readings / Work', label: 'Energy Readings / Work' },
  { value: 'Financial Advice', label: 'Financial Advice' },
  { value: 'Food / Groceries', label: 'Food / Groceries'},
  { value: 'Furniture / Appliances', label: 'Furniture / Appliances' },
  { value: 'General Care Packages', label: 'General Care Packages' },
  { value: 'Herbal Care', label: 'Herbal Care' },
  { value: 'Holistic Remedies', label: 'Holistic Remedies' },
  { value: 'Home Painting', label: 'Home Painting' },
  { value: 'Household Items', label: 'Household Items' },
  { value: 'Housing Availability', label: 'Housing Availability' },
  { value: 'Legal Help', label: 'Legal Help' },
  { value: 'Manual Labor', label: 'Manual Labor' },
  { value: 'Mechanical Assistance', label: 'Mechanical Assistance' },
  { value: 'Medical Care', label: 'Medical Care' },
  { value: 'Mental Health Resources', label: 'Mental Health Resources' },
  { value: 'Miscellaneous', label: 'Miscellaneous'},
  { value: 'Moving Help', label: 'Moving Help'},
  { value: 'Spiritual Tools', label: 'Spiritual Tools' },
  { value: 'Technical Help', label: 'Technical Help' },
  { value: 'Transportation', label: 'Transportation' },
  { value: 'Web Development', label: 'Web Development' },
]

export default categories