const serviceCities = [
  {value: "Online", label: "Online"},
  {value: "Aberdeen, SD", label: "Aberdeen, SD"},
  {value: "Abilene, TX", label: "Abilene, TX"},
  {value: "Akron, OH", label: "Akron, OH"},
  {value: "Albany, NY", label: "Albany, NY"},
  {value: "Albuquerque, NM", label: "Albuquerque, NM"},
  {value: "Alexandria, VA", label: "Alexandria, VA"},
  {value: "Allentown, PA", label: "Allentown, PA"},
  {value: "Amarillo, TX", label: "Amarillo, TX"},
  {value: "Anaheim, CA", label: "Anaheim, CA"},
  {value: "Anchorage, AL", label: "Anchorage, AL"},
  {value: "Ann Arbor, MI", label: "Ann Arbor, MI"},
  {value: "Antioch, CA", label: "Antioch, CA"},
  {value: "Apple Valley, CA", label: "Apple Valley, CA"},
  {value: "Appleton, WI", label: "Appleton, WI"},
  {value: "Arlington, TX", label: "Arlington, TX"},
  {value: "Arvada, CO", label: "Arvada, CO"},
  {value: "Asheville, NC", label: "Asheville, NC"},
  {value: "Athens, GA", label: "Athens, GA"},
  {value: "Atlanta, GA", label: "Atlanta, GA"},
  {value: "Atlantic City, NJ", label: "Atlantic City, NJ"},
  {value: "Augusta, GA", label: "Augusta, GA"},
  {value: "Aurora, CO", label: "Aurora, CO"},
  {value: "Austin, TX", label: "Austin, TX"},
  {value: "Bakersfield, CA", label: "Bakersfield, CA"},
  {value: "Baltimore, MD", label: "Baltimore, MD"},
  {value: "Barnstable, MA", label: "Barnstable, MA"},
  {value: "Baton Rouge, LA", label: "Baton Rouge, LA"},
  {value: "Beaumont, CA", label: "Beaumont, CA"},
  {value: "Bel Air, CA", label: "Bel Air, CA"},
  {value: "Bellevue, WA", label: "Bellevue, WA"},
  {value: "Berkeley, CA", label: "Berkeley, CA"},
  {value: "Bethlehem, PA", label: "Bethlehem, PA"},
  {value: "Billings, MT", label: "Billings, MT"},
  {value: "Birmingham, AL", label: "Birmingham, AL"},
  {value: "Bloomington, IN", label: "Bloomington, IN"},
  {value: "Boise, ID", label: "Boise, ID"},
  {value: "Boise City, OK", label: "Boise City, OK"},
  {value: "Bonita Springs, FL", label: "Bonita Springs, FL"},
  {value: "Boston, MA", label: "Boston, MA"},
  {value: "Boulder, CO", label: "Boulder, CO"},
  {value: "Bradenton, FL", label: "Bradenton, FL"},
  {value: "Bremerton, WA", label: "Bremerton, WA"},
  {value: "Bridgeport, CT", label: "Bridgeport, CT"},
  {value: "Brighton, MI", label: "Brighton, MI"},
  {value: "Brownsville, TX", label: "Brownsville, TX"},
  {value: "Bryan, TX", label: "Bryan, TX"},
  {value: "Buffalo, NY", label: "Buffalo, NY"},
  {value: "Burbank, CA", label: "Burbank, CA"},
  {value: "Burlington, VT", label: "Burlington, VT"},
  {value: "Cambridge, MA", label: "Cambridge, MA"},
  {value: "Canton, OH", label: "Canton, OH"},
  {value: "Cape Coral, FL", label: "Cape Coral, FL"},
  {value: "Carrollton, TX", label: "Carrollton, TX"},
  {value: "Cary, NC", label: "Cary, NC"},
  {value: "Cape Coral, FL", label: "Cape Coral, FL"},
  {value: "Cathedral City, CA", label: "Cathedral City, CA"},
  {value: "Cedar Rapids, IA", label: "Cedar Rapids, IA"},
  {value: "Champaign, IL", label: "Champaign, IL"},
  {value: "Chandler, AZ", label: "Chandler, AZ"},
  {value: "Charleston, SC", label: "Charleston, SC"},
  {value: "Charlotte, NC", label: "Charlotte, NC"},
  {value: "Chattanooga, TN", label: "Chattanooga, TN"},
  {value: "Chesapeake, VA", label: "Chesapeake, VA"},
  {value: "Chicago, IL", label: "Chicago, IL"},
  {value: "Chula Vista, CA", label: "Chula Vista, CA"},
  {value: "Cincinnati, OH", label: "Cincinnati, OH"},
  {value: "Clarke County, GA", label: "Clarke County, GA"},
  {value: "Clarksville, TN", label: "Clarksville, TN"},
  {value: "Clearwater, FL", label: "Clearwater, FL"},
  {value: "Cleveland, OH", label: "Cleveland, OH"},
  {value: "College Station, TX", label: "College Station, TX"},
  {value: "Colorado Springs, CO", label: "Colorado Springs, CO"},
  {value: "Columbia, SC", label: "Columbia, SC"},
  {value: "Columbus, OH", label: "Columbus, OH"},
  {value: "Concord, NH", label:  "Concord, NH"},
  {value: "Coral Springs, FL", label: "Coral Springs, FL"},
  {value: "Corona, CA", label: "Corona, CA"},
  {value: "Corpus Christi, TX", label: "Corpus Christi, TX"},
  {value: "Costa Mesa, CA", label: "Costa Mesa, CA"},
  {value: "Dallas, TX", label: "Dallas, TX"},
  {value: "Daly City, CA", label: "Daly City, CA"},
  {value: "Danbury, CT", label: "Danbury, CT"},
  {value: "Davenport, IA", label: "Davenport, IA"},
  {value: "Davidson County, NC", label: "Davidson County, NC"},
  {value: "Dayton, OH", label: "Dayton, OH"},
  {value: "Daytona Beach, FL", label: "Daytona Beach, FL"},
  {value: "Deltona, FL", label: "Deltona, FL"},
  {value: "Denton, TX", label: "Denton, TX"},
  {value: "Denver, CO", label: "Denver, CO"},
  {value: "Des Moines, IA", label: "Des Moines, IA"},
  {value: "Detroit, MI", label: "Detroit, MI"},
  {value: "Downey, CA", label: "Downey, CA"},
  {value: "Duluth, MN", label: "Duluth, MN"},
  {value: "Durham, NC", label: "Durham, NC"},
  {value: "El Monte, CA", label: "El Monte, CA"},
  {value: "El Paso, TX", label: "El Paso, TX"},
  {value: "Elizabeth, NJ", label: "Elizabeth, NJ"},
  {value: "Elk Grove, CA", label: "Elk Grove, CA"},
  {value: "Elkhart, IN", label: "Elkhart, IN"},
  {value: "Erie, PA", label: "Erie, PA"},
  {value: "Escondido, CA", label: "Escondido, CA"},
  {value: "Eugene, OR", label: "Eugene, OR"},
  {value: "Evansville, IN", label: "Evansville, IN"},
  {value: "Fairfield, CA", label: "Fairfield, CA"},
  {value: "Fargo, ND", label: "Fargo, ND"},
  {value: "Fayetteville, AR", label: "Fayetteville, AR"},
  {value: "Fitchburg, MA", label: "Fitchburg, MA"},
  {value: "Flint, MI", label: "Flint, MI"},
  {value: "Fontana, CA", label: "Fontana, CA"},
  {value: "Fort Collins, CO", label: "Fort Collins, CO"},
  {value: "Fort Lauderdale, FL", label: "Fort Lauderdale, FL"},
  {value: "Fort Smith, AR", label: "Fort Smith, AR"},
  {value: "Fort Walton Beach, FL", label: "Fort Walton Beach, FL"},
  {value: "Fort Wayne, IN", label: "Fort Wayne, IN"},
  {value: "Fort Worth, TX", label: "Fort Worth, TX"},
  {value: "Frederick, MD", label: "Frederick, MD"},
  {value: "Fremont, CA", label: "Fremont, CA"},
  {value: "Fresno, CA", label: "Fresno, CA"},
  {value: "Fullerton, CA", label: "Fullerton, CA"},
  {value: "Gainesville, FL", label: "Gainesville, FL"},
  {value: "Garden Grove, CA", label: "Garden Grove, CA"},
  {value: "Garland, TX", label: "Garland, TX"},
  {value: "Gastonia, NC", label: "Gastonia, NC"},
  {value: "Gilbert, AZ", label: "Gilbert, AZ"},
  {value: "Glendale, CA", label: "Glendale, CA"},
  {value: "Grand Prairie, TX", label: "Grand Prairie, TX"},
  {value: "Grand Rapids, MI", label: "Grand Rapids, MI"},
  {value: "Grayslake, IL", label: "Grayslake, IL"},
  {value: "Green Bay, WI", label: "Green Bay, WI"},
  {value: "Greensboro, NC", label: "Greensboro, NC"},
  {value: "Greenville, SC", label: "Greenville, SC"},
  {value: "Gulfport-Biloxi, MS", label: "Gulfport-Biloxi, MS"},
  {value: "Hagerstown, MD", label: "Hagerstown, MD"},
  {value: "Hampton, VA", label: "Hampton, VA"},
  {value: "Harlingen, TX", label: "Harlingen, TX"},
  {value: "Harrisburg, PA", label: "Harrisburg, PA"},
  {value: "Hartford, CT", label: "Hartford, CT"},
  {value: "Havre de Grace, MD", label: "Havre de Grace, MD"},
  {value: "Hayward, CA", label: "Hayward, CA"},
  {value: "Hemet, CA", label: "Hemet, CA"},
  {value: "Henderson, NV", label: "Henderson, NV"},
  {value: "Hesperia, CA", label: "Hesperia, CA"},
  {value: "Hialeah, FL", label: "Hialeah, FL"},
  {value: "Hickory, NC", label: "Hickory, NC"},
  {value: "High Point, NC", label: "High Point, NC"},
  {value: "Hollywood, CA", label: "Hollywood, CA"},
  {value: "Honolulu, HI", label: "Honolulu, HI"},
  {value: "Houma, LA", label: "Houma, LA"},
  {value: "Houston, TX", label: "Houston, TX"},
  {value: "Howell, NJ", label: "Howell, NJ"},
  {value: "Huntington, IN", label: "Huntington, IN"},
  {value: "Huntington Beach, CA", label: "Huntington Beach, CA"},
  {value: "Huntsville, AL", label: "Huntsville, AL"},
  {value: "Independence, MO", label: "Independence, MO"},
  {value: "Indianapolis, IN", label: "Indianapolis, IN"},
  {value: "Inglewood, CA", label: "Inglewood, CA"},
  {value: "Irvine, CA", label: "Irvine, CA"},
  {value: "Irving, TX", label: "Irving, TX"},
  {value: "Jackson, MS", label: "Jackson, MS"},
  {value: "Jacksonville, FL", label: "Jacksonville, FL"},
  {value: "Jefferson, MO", label: "Jefferson, MO"},
  {value: "Jersey City, NJ", label: "Jersey City, NJ"},
  {value: "Johnson City, TN", label: "Johnson City, TN"},
  {value: "Joliet, IL", label: "Joliet, IL"},
  {value: "Kailua, HI", label: "Kailua, HI"},
  {value: "Kalamazoo, MI", label: "Kalamazoo, MI"},
  {value: "Kaneohe, HI", label: "Kaneohe, HI"},
  {value: "Kansas City, MO", label: "Kansas City, MO"},
  {value: "Kennewick, WA", label: "Kennewick, WA"},
  {value: "Kenosha, WI", label: "Kenosha, WI"},
  {value: "Killeen, TX", label: "Killeen, TX"},
  {value: "Kissimmee, FL", label: "Kissimmee, FL"},
  {value: "Knoxville, TN", label: "Knoxville, TN"},
  {value: "Lacey, WA", label: "Lacey, WA"},
  {value: "Lafayette, IN", label: "Lafayette, IN"},
  {value: "Lafayette, LA", label: "Lafayette, LA"},
  {value: "Lake Charles, LA", label: "Lake Charles, LA"},
  {value: "Lakeland, FL", label: "Lakeland, FL"},
  {value: "Lakewood, CA", label: "Lakewood, CA"},
  {value: "Lancaster, PA", label: "Lancaster, PA"},
  {value: "Lansing, MI", label: "Lansing, MI"},
  {value: "Laredo, TX", label: "Laredo, TX"},
  {value: "Las Cruces, NM", label: "Las Cruces, NM"},
  {value: "Las Vegas, NV", label: "Las Vegas, NV"},
  {value: "Layton, UT", label: "Layton, UT"},
  {value: "Leominster, MA", label: "Leominster, MA"},
  {value: "Lewisville, TX", label: "Lewisville, TX"},
  {value: "Lexington, KT", label: "Lexington, KT"},
  {value: "Lincoln, NE", label: "Lincoln, NE"},
  {value: "Little Rock, AR", label: "Little Rock, AR"},
  {value: "Long Beach, CA", label: "Long Beach, CA"},
  {value: "Lorain, OH", label: "Lorain, OH"},
  {value: "Los Angeles, CA", label: "Los Angeles, CA"},
  {value: "Louisville, KT", label: "Louisville, KT"},
  {value: "Lowell, MA", label: "Lowell, MA"},
  {value: "Lubbock, TX", label: "Lubbock, TX"},
  {value: "Macon, GA", label: "Macon, GA"},
  {value: "Madison, WI", label: "Madison, WI"},
  {value: "Manchester, NH", label: "Manchester, NH"},
  {value: "Marina, CA", label: "Marina, CA"},
  {value: "Marysville, WA", label: "Marysville, WA"},
  {value: "McAllen, TX", label: "McAllen, TX"},
  {value: "McHenry, IL", label: "McHenry, IL"},
  {value: "Medford, OR", label: "Medford, OR"},
  {value: "Melbourne, FL", label: "Melbourne, FL"},
  {value: "Memphis, TN", label: "Memphis, TN"},
  {value: "Merced, CA", label: "Merced, CA"},
  {value: "Mesa, AZ", label: "Mesa, AZ"},
  {value: "Mesquite, TX", label: "Mesquite, TX"},
  {value: "Miami, FL", label: "Miami, FL"},
  {value: "Milwaukee, WI", label: "Milwaukee, WI"},
  {value: "Minneapolis, MN", label: "Minneapolis, MN"},
  {value: "Miramar, FL", label: "Miramar, FL"},
  {value: "Mission Viejo, CA", label: "Mission Viejo, CA"},
  {value: "Mobile, AL", label: "Mobile, AL"},
  {value: "Modesto, CA", label: "Modesto, CA"},
  {value: "Monroe, LA", label: "Monroe, LA"},
  {value: "Monterey, CA", label: "Monterey, CA"},
  {value: "Montgomery, AL", label: "Montgomery, AL"},
  {value: "Moreno Valley, CA", label: "Moreno Valley, CA"},
  {value: "Morgantown, WV", label: "Morgantown, WV"},
  {value: "Murfreesboro, TN", label: "Murfreesboro, TN"},
  {value: "Murrieta, CA", label: "Murrieta, CA"},
  {value: "Muskegon, MI", label: "Muskegon, MI"},
  {value: "Myrtle Beach, SC", label: "Myrtle Beach, SC"},
  {value: "Naperville, IL", label: "Naperville, IL"},
  {value: "Naples, FL", label: "Naples, FL"},
  {value: "Nashua, NH", label: "Nashua, NH"},
  {value: "Nashville, TN", label: "Nashville, TN"},
  {value: "New Bedford, MA", label: "New Bedford, MA"},
  {value: "New Haven, CT", label: "New Haven, CT"},
  {value: "New London, CT", label: "New London, CT"},
  {value: "New Orleans, LA", label: "New Orleans, LA"},
  {value: "New York, NY", label: "New York, NY"},
  {value: "Newark, NJ", label: "Newark, NJ"},
  {value: "Newburgh, NY", label: "Newburgh, NY"},
  {value: "Newport, RI", label: "Newport, RI"},
  {value: "Newport News, VA", label: "Newport News, VA"},
  {value: "Norfolk, VA", label: "Norfolk, VA"},
  {value: "Normal, IL", label: "Normal, IL"},
  {value: "Norman, OK", label: "Norman, OK"},
  {value: "North Charleston, SC", label: "North Charleston, SC"},
  {value: "North Las Vegas, NV", label: "North Las Vegas, NV"},
  {value: "North Port, FL", label: "North Port, FL"},
  {value: "Norwalk, CT", label: "Norwalk, CT"},
  {value: "Norwich, CT", label: "Norwich, CT"},
  {value: "Oakland, CA", label: "Oakland, CA"},
  {value: "Ocala, FL", label: "Ocala, FL"},
  {value: "Oceanside, CA", label: "Oceanside, CA"},
  {value: "Odessa, TX", label: "Odessa, TX"},
  {value: "Ogden, UT", label: "Ogden, UT"},
  {value: "Oklahoma City, OK", label: "Oklahoma City, OK"},
  {value: "Olathe, KS", label: "Olathe, KS"},
  {value: "Olympia, WA", label: "Olympia, WA"},
  {value: "Omaha, NE", label: "Omaha, NE"},
  {value: "Ontario, CA", label: "Ontario, CA"},
  {value: "Orange, CA", label: "Orange, CA"},
  {value: "Orem, UT", label: "Orem, UT"},
  {value: "Orlando, FL", label: "Orlando, FL"},
  {value: "Overland Park, KS", label: "Overland Park, KS"},
  {value: "Oxnard, CA", label: "Oxnard, CA"},
  {value: "Palm Bay, FL", label: "Palm Bay, FL"},
  {value: "Palm Springs, CA", label: "Palm Springs, CA"},
  {value: "Palmdale, CA", label: "Palmdale, CA"},
  {value: "Panama City, FL", label: "Panama City, FL"},
  {value: "Pasadena, CA", label: "Pasadena, CA"},
  {value: "Paterson, NJ", label: "Paterson, NJ"},
  {value: "Pembroke Pines, FL", label: "Pembroke Pines, FL"},
  {value: "Pensacola, FL", label: "Pensacola, FL"},
  {value: "Peoria, IL", label: "Peoria, IL"},
  {value: "Philadelphia, PA", label: "Philadelphia, PA"},
  {value: "Phoenix, AZ", label: "Phoenix, AZ"},
  {value: "Pittsburgh, PA", label: "Pittsburgh, PA"},
  {value: "Plano, TX", label: "Plano, TX"},
  {value: "Pomona, CA", label: "Pomona, CA"},
  {value: "Pompano Beach, FL", label: "Pompano Beach, FL"},
  {value: "Port Arthur, TX", label: "Port Arthur, TX"},
  {value: "Port Orange, FL", label: "Port Orange, FL"},
  {value: "Port St. Lucie, FL", label: "Port St. Lucie, FL"},
  {value: "Portland, OR", label: "Portland, OR"},
  {value: "Portsmouth, NH", label: "Portsmouth, NH"},
  {value: "Poughkeepsie, NY", label: "Poughkeepsie, NY"},
  {value: "Providence, RI", label: "Providence, RI"},
  {value: "Provo, UT", label: "Provo, UT"},
  {value: "Pueblo, CO", label: "Pueblo, CO"},
  {value: "Punta Gorda, FL", label: "Punta Gorda, FL"},
  {value: "Racine, WI", label: "Racine, WI"},
  {value: "Raleigh, NC", label: "Raleigh, NC"},
  {value: "Rancho Cucamonga, CA", label: "Rancho Cucamonga, CA"},
  {value: "Reading, PA", label: "Reading, PA"},
  {value: "Redding, CA", label: "Redding, CA"},
  {value: "Reno, NV", label: "Reno, NV"},
  {value: "Richland, WA", label: "Richland, WA"},
  {value: "Richmond, VA", label: "Richmond, VA"},
  {value: "Richmond County, GA", label: "Richmond County, GA"},
  {value: "Riverside, CA", label: "Riverside, CA"},
  {value: "Roanoke, VA", label: "Roanoke, VA"},
  {value: "Rochester, NY", label: "Rochester, NY"},
  {value: "Rockford, IL", label: "Rockford, IL"},
  {value: "Roseville, CA", label: "Roseville, CA"},
  {value: "Round Lake Beach, IL", label: "Round Lake Beach, IL"},
  {value: "Sacramento, CA", label: "Sacramento, CA"},
  {value: "Saginaw, MI", label: "Saginaw, MI"},
  {value: "Salem, MA", label: "Salem, MA"},
  {value: "Salinas, CA", label: "Salinas, CA"},
  {value: "Salt Lake City, UT", label: "Salt Lake City, UT"},
  {value: "San Antonio, TX", label: "San Antonio, TX"},
  {value: "San Bernardino, CA", label: "San Bernardino, CA"},
  {value: "San Diego, CA", label: "San Diego, CA"},
  {value: "San Francisco, CA", label: "San Francisco, CA"},
  {value: "San Jose, CA", label: "San Jose, CA"},
  {value: "Santa Ana, CA", label: "Santa Ana, CA"},
  {value: "Santa Barbara, CA", label: "Santa Barbara, CA"},
  {value: "Santa Clara, CA", label: "Santa Clara, CA"},
  {value: "Santa Clarita, CA", label: "Santa Clarita, CA"},
  {value: "Santa Cruz, CA", label: "Santa Cruz, CA"},
  {value: "Santa Maria, CA", label: "Santa Maria, CA"},
  {value: "Santa Rosa, CA", label: "Santa Rosa, CA"},
  {value: "Sarasota, FL", label: "Sarasota, FL"},
  {value: "Savannah, GA", label: "Savannah, GA"},
  {value: "Scottsdale, AZ", label: "Scottsdale, AZ"},
  {value: "Scranton, PA", label: "Scranton, PA"},
  {value: "Seaside, OR", label: "Seaside, OR"},
  {value: "Seattle, WA", label: "Seattle, WA"},
  {value: "Sebastian, FL", label: "Sebastian, FL"},
  {value: "Shreveport, LA", label: "Shreveport, LA"},
  {value: "Simi Valley, CA", label: "Simi Valley, CA"},
  {value: "Sioux City, IA", label: "Sioux City, IA"},
  {value: "Sioux Falls, SD", label: "Sioux Falls, SD"},
  {value: "South Bend, IN", label: "South Bend, IN"},
  {value: "South Lyon, MI", label: "South Lyon, MI"},
  {value: "Spartanburg, SC", label: "Spartanburg, SC"},
  {value: "Spokane, WA", label: "Spokane, WA"},
  {value: "Springdale, AR", label: "Springdale, AR"},
  {value: "Springfield, IL", label: "Springfield, IL"},
  {value: "Springfield, MA", label: "Springfield, MA"},
  {value: "St. Louis, MO", label: "St. Louis, MO"},
  {value: "St. Paul, MN", label: "St. Paul, MN"},
  {value: "St. Petersburg, FL", label: "St. Petersburg, FL"},
  {value: "Stamford, CT", label: "Stamford, CT"},
  {value: "Sterling Heights, MI", label: "Sterling Heights, MI"},
  {value: "Stockton, CA", label: "Stockton, CA"},
  {value: "Sunnyvale, CA", label: "Sunnyvale, CA"},
  {value: "Syracuse, NY", label: "Syracuse, NY"},
  {value: "Tacoma, WA", label: "Tacoma, WA"},
  {value: "Tallahassee, FL", label: "Tallahassee, FL"},
  {value: "Tampa, FL", label: "Tampa, FL"},
  {value: "Temecula, CA", label: "Temecula, CA"},
  {value: "Tempe, AZ", label: "Tempe, AZ"},
  {value: "Thornton, CO", label: "Thornton, CO"},
  {value: "Thousand Oaks, CA", label: "Thousand Oaks, CA"},
  {value: "Toledo, OH", label: "Toledo, OH"},
  {value: "Topeka, KS", label: "Topeka, KS"},
  {value: "Torrance, CA", label: "Torrance, CA"},
  {value: "Trenton, NJ", label: "Trenton, NJ"},
  {value: "Tucson, AZ", label: "Tucson, AZ"},
  {value: "Tulsa, OK", label: "Tulsa, OK"},
  {value: "Tuscaloosa, AL", label: "Tuscaloosa, AL"},
  {value: "Tyler, TX", label: "Tyler, TX"},
  {value: "Utica, NY", label: "Utica, NY"},
  {value: "Vallejo, CA", label: "Vallejo, CA"},
  {value: "Vancouver, WA", label: "Vancouver, WA"},
  {value: "Ventura, CA", label: "Ventura, CA"},
  {value: "Vero Beach, FL", label: "Vero Beach, FL"},
  {value: "Victorville, CA", label: "Victorville, CA"},
  {value: "Virginia Beach, VA", label: "Virginia Beach, VA"},
  {value: "Visalia, CA", label: "Visalia, CA"},
  {value: "Waco, TX", label: "Waco, TX"},
  {value: "Warren, MI", label: "Warren, MI"},
  {value: "Washington, D.C.", label: "Washington, D.C."},
  {value: "Waterbury, CT", label: "Waterbury, CT"},
  {value: "Waterloo, IA", label: "Waterloo, IA"},
  {value: "West Covina, CA", label: "West Covina, CA"},
  {value: "West Valley City, UT", label: "West Valley City, UT"},
  {value: "Westminster, CO", label: "Westminster, CO"},
  {value: "Wichita, KS", label: "Wichita, KS"},
  {value: "Wilmington, DE", label: "Wilmington, DE"},
  {value: "Winston, NC", label: "Winston, NC"},
  {value: "Winter Haven, FL", label: "Winter Haven, FL"},
  {value: "Worcester, MA", label: "Worcester, MA"},
  {value: "Yakima, WA", label: "Yakima, WA"},
  {value: "Yonkers, NY", label: "Yonkers, NY"},
  {value: "York, PA", label: "York, PA"},
  {value: "Youngstown, WV", label: "Youngstown, WV"},
]

export default serviceCities