const serviceCategories = [
    { value: 'microphones', label: 'Microphones' },
    { value: 'microphone accesories', label: 'Microphone accessories' },
    { value: 'digital cameras', label: 'Digital cameras' },
    { value: 'film cameras', label: 'Film cameras' },
    { value: 'lenses', label: 'Lenses' },
    { value: 'audio cables', label: 'Audio cables' },
    { value: 'video cables', label: 'Video cables' },
    { value: 'power supply', label: 'Power supply' },
    { value: 'amplifiers', label: 'Amplifiers' },
    { value: 'subwoofers', label: 'Subwoofers' },
    { value: 'midi controllers', label: 'Midi controllers' },
    { value: 'preamps', label: 'Preamps' },
    { value: 'audio interfaces', label: 'Audio interfaces' },
    { value: 'VFX equipment', label: 'VFX equipment' },
    { value: 'headphones', label: 'Headphones' },
    { value: 'mixers', label: 'Mixers' },
    { value: 'combo amps, heads and cabs', label: 'Combo amps, heads and cabs' },
    { value: 'misc equipment', label: 'Misc equipment' },
    { value: 'speakers', label: 'Speakers' },
    { value: 'monitors', label: 'Monitors' },
    { value: 'tools', label: 'Tools' },
    { value: 'truss', label: 'Truss' },
    { value: 'rigging', label: 'Rigging' },
    { value: 'speed rail', label: 'Speed rail' },
    { value: 'dollies', label: 'Dollies' },
    { value: 'grip equipment', label: 'Grip equipment' },
    { value: 'apple boxes', label: 'Apple boxes' },
    { value: 'sand bags', label: 'Sand bags' },
    { value: 'grip stands', label: 'Grip stands' },
    { value: 'reflectors', label: 'Reflector' },
    { value: 'scrims', label: 'Scrims' },
    { value: 'flags', label: 'Flags' },
    { value: 'boxes', label: 'Boxes' },
    { value: 'carts', label: 'Carts' },
    { value: 'HMI lighting', label: 'HMI lighting' },
    { value: 'LED lighting', label: 'LED lighting' },
    { value: 'conventional lighting', label: 'Conventional lighting' },
    { value: 'flourescent lighting', label: 'Flourescent lighting' },
    { value: 'adapters', label: 'Adapters' },
    { value: 'dimming', label: 'Dimming' },
    { value: 'chimeras', label: 'Chimeras' },
    { value: 'data cables', label: 'Data cables' },
    { value: 'special FX', label: 'special FX' },
    { value: 'communication', label: 'Communication' },
    { value: 'DI boxes', label: 'DI boxes' },
    { value: 'safety equipment', label: 'Safety equipment' },
    { value: 'atmospheric equipment', label: 'Atmospheric equipment' },
    { value: 'chairs and tables', label: 'Chairs and tables' },
  ]

export default serviceCategories